os:
  - linux
sudo: false
addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
before_install: 
  - cd erp_ranger_app
before_script:
  - git clone https://github.com/flutter/flutter.git -b v1.2.1
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
script:
  - ./flutter/bin/flutter test test/full_test.dart
cache:
  directories:
    - $HOME/.pub-cache